use tw_macro::tw;
classes! {
    base: tw![
        "grid",
        "grid-cols-[6.5rem_1fr]",
        "items-start",
        "gap-x-4",
        "mb-0",
        "pb-2",
        "border-b",
        "border-warcraft-blue-deep",
    ],
    mobile: tw![
        "mobile:flex",
        "mobile:flex-row",
        "mobile:items-start",
        "mobile:h-auto",
        "mobile:min-h-0",
        "mobile:gap-3",
        "mobile:pb-4",
        "mobile:overflow-visible",
        "mobile:text-left",
        "mobile:w-full",
        "mobile:min-w-0",
    ],
    tablet: tw![
        "tablet:flex",
        "tablet:flex-row",
        "tablet:items-start",
        "tablet:h-auto",
        "tablet:min-h-0",
        "tablet:gap-3",
        "tablet:pb-4",
        "tablet:overflow-visible",
        "tablet:text-left",
        "tablet:w-full",
        "tablet:min-w-0",
    ],
}
