use tw_macro::tw;
classes! {
    base: tw![
        "absolute",
        "top-[calc(100%+4px)]",
        "left-0",
        "z-[200]",
        "min-w-full",
        "flex",
        "flex-col",
        "gap-[2px]",
        "p-[4px]",
        "[background:linear-gradient(170deg,color-mix(in_oklab,var(--color-warcraft-bg-mid)_98%,transparent)_0%,color-mix(in_oklab,var(--color-warcraft-bg-base)_98%,transparent)_100%)]",
        "border",
        "border-warcraft-gold/45",
        "rounded-card",
        "[box-shadow:0_8px_24px_color-mix(in_oklab,var(--color-warcraft-shadow)_65%,transparent),0_0_12px_color-mix(in_oklab,var(--color-warcraft-gold)_10%,transparent)]",
    ],
    mobile: tw![
        "mobile:w-full",
        "mobile:max-h-[min(320px,65dvh)]",
        "mobile:overflow-y-auto",
        "mobile:[overscroll-behavior:contain]",
        "mobile:[scrollbar-width:none]",
        "mobile:[&::-webkit-scrollbar]:hidden",
    ],
    tablet: tw![
        "tablet:w-full",
        "tablet:max-h-[min(320px,65dvh)]",
        "tablet:overflow-y-auto",
        "tablet:[overscroll-behavior:contain]",
        "tablet:[scrollbar-width:none]",
        "tablet:[&::-webkit-scrollbar]:hidden",
    ],
}
