use tw_macro::tw;

classes! {
    base: tw![
        "inline-flex",
        "items-center",
        "justify-center",
        "gap-[4.27cqi]",
        "size-full",
        "px-[8.55cqi]",
        "border-[0.3cqi]",
        "border-warcraft-gold",
        "rounded-[3.2cqi]",
        "text-warcraft-gold",
        "text-[8.55cqi]",
        "tracking-eyebrow",
        "font-medium",
        "cursor-pointer",
        "bg-panel-gold-resting",
        "shadow-glow-soft",
        "transition-[background,box-shadow,transform]",
        "duration-fast",
        "focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]",
        "kb-focus:shadow-focus",
        "hover:bg-panel-gold-active",
        "hover:shadow-glow-strong",
    ],
}
