use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "flex-col",
        "gap-9",
        "py-10",
        "px-11",
        "border",
        "border-warcraft-gold-border",
        "rounded-container",
        "text-left",
        "text-warcraft-text-secondary",
        "bg-panel-gold-resting",
        "cursor-pointer",
        "transition-interactive",
        "duration-base",
        "ease-[ease]",
        "hover:border-warcraft-gold",
        "hover:text-warcraft-gold",
        "hover:bg-panel-gold-active",
        "hover:shadow-glow",
        "focus:outline-none",
        "kb-focus:outline-none",
        "kb-focus:border-warcraft-highlight",
        "kb-focus:text-warcraft-highlight",
        "kb-focus:shadow-focus",
    ],
    mobile: tw![
        "mobile:gap-2.5",
        "mobile:py-3",
        "mobile:px-3.5",
        "mobile:rounded-panel",
    ],
    tablet: tw![
        "tablet:gap-2.5",
        "tablet:py-3",
        "tablet:px-3.5",
        "tablet:rounded-panel",
    ],
}
