use tw_macro::tw;

classes! {
    base: tw![
        "uppercase",
        "tracking-heading",
        "text-2xl",
        "leading-none",
        "px-3",
        "py-1",
        "m-0",
        "bg-transparent",
        "border-0",
        "cursor-pointer",
        "whitespace-nowrap",
        "text-shadow-drop",
        "transition-[color,text-shadow]",
        "hover:text-warcraft-gold",
        "hover:text-shadow-glow",
        "kb-focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:[text-shadow:1px_1px_0_var(--color-warcraft-shadow),0_0_14px_color-mix(in_oklab,var(--color-warcraft-highlight)_65%,transparent)]",
        "group-data-[open=true]:flex-none",
        "group-data-[open=true]:w-full",
        "group-data-[open=true]:text-left",
        "group-data-[open=true]:py-3",
        "group-data-[open=true]:px-3.5",
        "group-data-[open=true]:text-base",
        "group-data-[open=true]:tracking-label",
        "group-data-[open=true]:min-h-11",
        "group-data-[open=true]:rounded-tile",
        "group-data-[open=true]:whitespace-normal",
        "text-warcraft-gold",
        "[text-shadow:1px_1px_0_var(--color-warcraft-shadow),0_0_16px_color-mix(in_oklab,var(--color-warcraft-gold)_45%,transparent)]",
        "group-data-[open=true]:bg-warcraft-gold/14",
        "group-data-[open=true]:shadow-ring",
    ],
}
