use tw_macro::tw;
classes! {
    base: tw![
        "absolute",
        "right-4",
        "top-1/2",
        "-translate-y-1/2",
        "w-10",
        "h-10",
        "text-xl",
        "flex",
        "items-center",
        "justify-center",
        "bg-transparent",
        "border-0",
        "cursor-pointer",
        "text-warcraft-text-secondary",
        "text-shadow-drop",
        "transition-[color,text-shadow]",
        "duration-base",
        "hover:text-warcraft-gold",
        "hover:text-shadow-glow",
        "focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:[--glow-color:var(--color-warcraft-highlight)]",
        "kb-focus:text-glow",
    ],
}
