use tw_macro::tw;

classes! {
    base: tw![
        "size-full",
        "flex",
        "items-center",
        "justify-center",
        "p-0",
        "border-2",
        "border-warcraft-gold",
        "bg-warcraft-gold-dark/75",
        "text-warcraft-gold",
        "text-shadow-outline",
        "uppercase",
        "leading-none",
        "text-center",
        "transition-[box-shadow,border-color,background,color]",
        "duration-base",
        "rounded-(--keycap-radius,var(--radius-panel))",
        "hover:border-warcraft-gold",
        "hover:bg-warcraft-gold/12",
        "hover:shadow-glow-soft",
        "group-focus-visible/editable-keycap:border-white",
        "group-focus-visible/editable-keycap:text-white",
        "group-focus-visible/editable-keycap:shadow-focus",
        "[@media(hover:none)]:group-focus-visible/editable-keycap:border-warcraft-gold",
        "[@media(hover:none)]:group-focus-visible/editable-keycap:bg-warcraft-gold-dark/75",
        "[@media(hover:none)]:group-focus-visible/editable-keycap:text-warcraft-gold",
        "[@media(hover:none)]:group-focus-visible/editable-keycap:shadow-none",
    ],
}
