use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "items-center",
        "gap-4",
        "p-4",
        "w-full",
        "min-w-0",
        "text-left",
        "text-lg",
        "tracking-snug",
        "border",
        "rounded-tile",
        "transition-all",
        "duration-fast",
        "bg-warcraft-bg-mid/55",
        "text-warcraft-text-primary",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:bg-warcraft-blue/85",
        "kb-focus:shadow-focus",
        "border-warcraft-blue-deep",
        "hover:bg-warcraft-blue-deep/70",
        "hover:text-white",
        "hover:border-(--race-color)",
    ],
    tablet: tw![
        "tablet:h-full",
        "tablet:py-2",
        "tablet:px-2.5",
        "tablet:gap-2.5",
        "tablet:box-border",
        "tablet:overflow-hidden",
        "tablet:bg-panel-dark",
        "tablet:border-warcraft-blue/60",
    ],
}
