use tw_macro::tw;
classes! {
    base: tw![
        "relative",
        "isolate",
        "w-full",
        "aspect-square",
        "@container",
        "overflow-hidden",
        "border-(length:--tile-border-width,2px)",
        "rounded-(--tile-corner-radius,var(--radius-tile))",
        "border-warcraft-blue",
        "shadow-bevel",
        "transition-[border-color,box-shadow]",
        "duration-fast",
        "touch-pan-y",
        "outline-none",
        "hover:border-(--race-color,var(--color-warcraft-gold))",
        "active:border-(--race-color,var(--color-warcraft-gold))",
        "kb-focus:border-warcraft-gold",
        "kb-focus:shadow-focus",
        "has-[.selection-ring]:border-(--race-color,var(--color-warcraft-gold))",
        "has-[.selection-ring]:shadow-glow",
        "has-[.selection-ring]:[--glow-color:var(--race-color,var(--color-warcraft-gold))]",
        "has-[.dragging-source-ghost]:border-warcraft-blue-deep",
        "has-[.dragging-source-ghost]:border-dashed",
        "has-[.dragging-source-ghost]:bg-panel-dark",
        "[&:has(.dragging-source-ghost)>*]:invisible",
        "has-[.drag-over-ring]:border-warcraft-gold",
        "has-[.drag-over-ring]:border-solid",
        "[&:has(.dragging-source-ghost):has(.drag-over-ring)]:border-warcraft-gold",
        "[&:has(.dragging-source-ghost):has(.drag-over-ring)]:border-dashed",
        "[body:has(.dragging-source-ghost)_&]:transition-none",
    ],
}
