services:
  hotkey-editor:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: "moon run hotkey-editor:dx/serve-container"
    stdin_open: true
    tty: true
    environment:
      FORCE_COLOR: "1"
      RUSTUP_TOOLCHAIN: "1.95.0-x86_64-unknown-linux-gnu"
    volumes:
      - .:/app
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
      - target:/app/target
      - moon-cache:/app/.moon/cache
      - root-node-modules:/app/node_modules
      - hotkey-editor-node-modules:/app/crates/hotkey-editor/node_modules
      - moon-home:/root/.moon
    ports:
      - "8080:8080"

volumes:
  cargo-registry:
  cargo-git:
  target:
  moon-cache:
  root-node-modules:
  hotkey-editor-node-modules:
  moon-home:
