use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "items-baseline",
        "justify-center",
        "flex-wrap",
        "gap-3",
        "flex-[1_1_auto]",
    ],
    mobile: tw![
        "mobile:flex",
        "mobile:absolute",
        "mobile:top-[calc(100%-0.25rem)]",
        "mobile:left-3",
        "mobile:right-3",
        "mobile:z-6",
        "mobile:flex-col",
        "mobile:items-stretch",
        "mobile:gap-0.5",
        "mobile:p-1.5",
        "mobile:bg-panel-dark",
        "mobile:border",
        "mobile:border-warcraft-gold/45",
        "mobile:rounded-panel",
        "mobile:shadow-overlay",
    ],
    tablet: tw![
        "tablet:flex",
        "tablet:absolute",
        "tablet:top-[calc(100%-0.25rem)]",
        "tablet:left-3",
        "tablet:right-3",
        "tablet:z-6",
        "tablet:flex-col",
        "tablet:items-stretch",
        "tablet:gap-0.5",
        "tablet:p-1.5",
        "tablet:bg-panel-dark",
        "tablet:border",
        "tablet:border-warcraft-gold/45",
        "tablet:rounded-panel",
        "tablet:shadow-overlay",
    ],
}
