use tw_macro::tw;

classes! {
    base: tw![
        "@container",
        "relative",
        "flex-none",
        "flex",
        "flex-wrap",
        "items-center",
        "justify-center",
        "tracking-snug",
        "select-none",
        "px-4",
        "gap-x-[0.9em]",
        "gap-y-2.5",
        "py-2.5",
        "leading-heading",
        "text-center",
        "text-white/60",
        "text-xs",
        "before:content-['']",
        "before:absolute",
        "before:top-0",
        "before:left-4",
        "before:right-4",
        "before:h-px",
        "before:bg-warcraft-gold/40",
        "before:shadow-edge",
    ],
}
