use tw_macro::tw;

classes! {
    base: tw![
        "@container",
        "relative",
        "flex-none",
        "flex",
        "flex-wrap",
        "items-center",
        "justify-center",
        "tracking-snug",
        "select-none",
        "px-4",
        "gap-x-[0.9em]",
        "gap-y-2.5",
        "py-2.5",
        "leading-heading",
        "text-center",
        "text-white/60",
        "text-xs",
        "before:content-['']",
        "before:absolute",
        "before:top-0",
        "before:left-4",
        "before:right-4",
        "before:h-px",
        "before:bg-warcraft-gold/40",
        "before:shadow-edge",
    ],
    mobile: tw![
        "mobile:overflow-hidden",
        "mobile:max-h-18",
        "mobile:py-1",
        "mobile:gap-x-[0.55em]",
        "mobile:gap-y-0.5",
        "mobile:text-[0.6rem]",
        "mobile:leading-tight",
        "mobile:transition-[max-height,padding,opacity]",
        "mobile:duration-300",
        "mobile:ease-out",
        "mobile:has-[.footer-scroll-tuck]:max-h-0",
        "mobile:has-[.footer-scroll-tuck]:py-0",
        "mobile:has-[.footer-scroll-tuck]:opacity-0",
    ],
}
