use tw_macro::tw;
classes! {
    base: tw![
        "hidden",
        "kb-focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:shadow-ring-hl",
    ],
    mobile: tw![
        "mobile:flex",
        "mobile:items-center",
        "mobile:justify-between",
        "mobile:gap-2.5",
        "mobile:w-full",
        "mobile:min-h-[44px]",
        "mobile:py-2",
        "mobile:px-3.5",
        "mobile:border",
        "mobile:border-warcraft-gold/55",
        "mobile:rounded-card",
        "mobile:cursor-pointer",
        "mobile:uppercase",
        "mobile:text-warcraft-gold",
        "mobile:text-base",
        "mobile:tracking-[0.06em]",
        "mobile:bg-panel-gold-diag-85",
        "mobile:text-shadow-drop-92",
        "mobile:shadow-glow-14",
    ],
    tablet: tw![
        "tablet:flex",
        "tablet:items-center",
        "tablet:justify-between",
        "tablet:gap-2.5",
        "tablet:w-full",
        "tablet:min-h-[44px]",
        "tablet:py-2",
        "tablet:px-3.5",
        "tablet:border",
        "tablet:border-warcraft-gold/55",
        "tablet:rounded-card",
        "tablet:cursor-pointer",
        "tablet:uppercase",
        "tablet:text-warcraft-gold",
        "tablet:text-base",
        "tablet:tracking-[0.06em]",
        "tablet:bg-panel-gold-diag-85",
        "tablet:text-shadow-drop-92",
        "tablet:shadow-glow-14",
    ],
}
