use tw_macro::tw;
classes! {
    base: tw![
        "absolute",
        "top-[calc(100%+4px)]",
        "left-0",
        "z-20",
        "min-w-full",
        "flex",
        "flex-col",
        "gap-0.5",
        "p-1",
        "bg-panel-toast",
        "border",
        "border-warcraft-gold/45",
        "rounded-card",
        "shadow-overlay",
    ],
    mobile: tw![
        "mobile:w-full",
        "mobile:max-h-80",
        "mobile:overflow-y-auto",
        "mobile:overscroll-contain",
        "mobile:scrollbar-none",
        "mobile:[&::-webkit-scrollbar]:hidden",
    ],
    tablet: tw![
        "tablet:w-full",
        "tablet:max-h-80",
        "tablet:overflow-y-auto",
        "tablet:overscroll-contain",
        "tablet:scrollbar-none",
        "tablet:[&::-webkit-scrollbar]:hidden",
    ],
}
