use super::state::InventoryCellState;
use tw_macro::tw;

classes! {
    base: tw![
        "relative",
        "flex",
        "flex-col",
        "items-center",
        "justify-center",
        "gap-[0.45rem]",
        "px-[0.6rem]",
        "py-[0.85rem]",
        "cursor-pointer",
        "text-center",
        "select-none",
        "border-solid",
        "border-[12px]",
        "bg-panel-dark-85",
        "[border-image-source:var(--wc3-slot-frame)]",
        "[border-image-slice:12_fill]",
        "[border-image-repeat:stretch]",
        "[touch-action:none]",
        "[transition:filter_0.15s_ease]",
        "[&:hover]:[filter:brightness(1.18)_drop-shadow(0_0_8px_color-mix(in_oklab,var(--color-warcraft-gold)_45%,transparent))]",
        "focus:outline-none",
        "kb-focus:outline-none",
        "kb-focus:[filter:brightness(1.25)_drop-shadow(0_0_10px_color-mix(in_oklab,var(--color-warcraft-highlight)_55%,transparent))]",
        "data-[dragging=true]:[&>*]:invisible",
        "after:[content:attr(data-tooltip)]",
        "after:absolute",
        "after:bottom-[calc(100%+0.6rem)]",
        "after:left-1/2",
        "after:-translate-x-1/2",
        "after:w-max",
        "after:max-w-[38rem]",
        "after:px-[1.1rem]",
        "after:py-3",
        "after:border",
        "after:border-warcraft-gold",
        "after:rounded-[4px]",
        "after:bg-panel-dark-solid",
        "after:text-warcraft-gold",
        "after:text-[1.5rem]",
        "after:leading-[1.4]",
        "after:text-center",
        "after:text-shadow-drop",
        "after:shadow-elevation",
        "after:whitespace-normal",
        "after:pointer-events-none",
        "after:z-[1200]",
        "after:opacity-0",
        "after:transition-opacity",
        "after:duration-150",
        "after:delay-[400ms]",
        "[&[data-tooltip]:not([data-tooltip=''])]:hover:after:opacity-100",
        "[&[data-tooltip]:not([data-tooltip=''])]:focus-visible:after:opacity-100",
    ],
    mobile: tw![
        "mobile:border-[8px]",
        "mobile:px-[0.3rem]",
        "mobile:py-[0.45rem]",
        "mobile:gap-[0.25rem]",
        "mobile:aspect-[1/0.85]",
        "mobile:min-h-0",
    ],
    tablet: tw![
        "tablet:border-[8px]",
        "tablet:px-[0.3rem]",
        "tablet:py-[0.45rem]",
        "tablet:gap-[0.25rem]",
        "tablet:aspect-[1/0.85]",
        "tablet:min-h-0",
    ],
}

states! {
    InventoryCellState,
    Idle => tw![],
    Active => tw!["[filter:brightness(1.32)_drop-shadow(0_0_14px_color-mix(in_oklab,var(--color-warcraft-gold)_75%,transparent))]"],
    Conflict => tw!["[filter:drop-shadow(0_0_12px_color-mix(in_oklab,var(--color-warcraft-danger)_55%,transparent))]"],
}
