use tw_macro::tw;
// The burger appears at a single size (the compact header, hidden at laptop and up),
// so its chrome is fixed rather than cqi — there is no size change to scale against.

classes! {
    base: tw![
        "inline-flex",
        "items-center",
        "justify-center",
        "shrink-0",
        "self-center",
        "p-0",
        "w-9",
        "h-9",
        "min-w-9",
        "min-h-9",
        "bg-panel-gold-resting",
        "border",
        "border-warcraft-gold-border",
        "rounded-tile",
        "text-warcraft-text-secondary",
        "cursor-pointer",
        "transition-[border-color,color,background,box-shadow]",
        "hover:border-warcraft-gold",
        "hover:text-warcraft-gold",
        "hover:bg-panel-gold-active",
        "hover:shadow-glow",
        "focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:shadow-focus",
    ],
    laptop: tw!["laptop:hidden"],
    desktop: tw!["desktop:hidden"],
    qhd: tw!["qhd:hidden"],
    uhd: tw!["uhd:hidden"],
}
