use tw_macro::tw;
// The scroll region around the track. Vertical scroll on the sidebar with a gold
// scrollbar that fades in on hover of the list; horizontal snap scroll (the swipe
// carousel) on small screens with the scrollbar hidden. The list group's hover
// drives the scrollbar reveal.

classes! {
    base: tw![
        "flex-1",
        "flex",
        "flex-col",
        "min-h-0",
        "overflow-y-auto",
        "overflow-x-hidden",
        "pr-1",
        "scrollbar-thin",
        "[scrollbar-color:color-mix(in_oklab,var(--color-warcraft-gold)_0%,transparent)_transparent]",
        "transition-[scrollbar-color]",
        "duration-slow",
        "group-hover:[scrollbar-color:color-mix(in_oklab,var(--color-warcraft-gold)_45%,transparent)_transparent]",
        "[&::-webkit-scrollbar]:w-1.5",
        "[&::-webkit-scrollbar-track]:bg-transparent",
        "[&::-webkit-scrollbar-thumb]:bg-transparent",
        "[&::-webkit-scrollbar-thumb]:rounded-hairline",
        "group-hover:[&::-webkit-scrollbar-thumb]:bg-warcraft-gold/45",
        "[&::-webkit-scrollbar-thumb:hover]:bg-warcraft-gold",
    ],
    mobile: tw![
        "mobile:overflow-x-auto",
        "mobile:overflow-y-hidden",
        "mobile:max-h-none",
        "mobile:pr-0",
        "mobile:pb-1",
        "mobile:flex-none",
        "mobile:@container",
        "mobile:h-28",
        "mobile:[-webkit-overflow-scrolling:touch]",
        "mobile:overscroll-x-contain",
        "mobile:[scroll-snap-type:x_mandatory]",
        "mobile:scrollbar-none",
        "mobile:scroll-ps-[0.4rem]",
        "mobile:[&::-webkit-scrollbar]:hidden",
    ],
    tablet: tw![
        "tablet:overflow-x-auto",
        "tablet:overflow-y-hidden",
        "tablet:max-h-none",
        "tablet:pr-0",
        "tablet:pb-1",
        "tablet:flex-none",
        "tablet:@container",
        "tablet:h-30",
        "tablet:[-webkit-overflow-scrolling:touch]",
        "tablet:overscroll-x-contain",
        "tablet:[scroll-snap-type:x_mandatory]",
        "tablet:scrollbar-none",
        "tablet:scroll-ps-[0.4rem]",
        "tablet:[&::-webkit-scrollbar]:hidden",
    ],
}
