use super::state::FilledTileState;
use tw_macro::tw;

classes! {
    base: tw![
        "relative",
        "w-full",
        "aspect-square",
        "@container",
        "overflow-hidden",
        "border-[2cqi]",
        "rounded-[5.2cqi]",
        "transition-[border-color,box-shadow]", "duration-fast",
        "touch-pan-y",
        "outline-none",
        "hover:border-warcraft-gold",
        "active:border-warcraft-gold",
        "data-[race=human]:hover:border-race-human",
        "data-[race=human]:active:border-race-human",
        "data-[race=orc]:hover:border-race-orc",
        "data-[race=orc]:active:border-race-orc",
        "data-[race=nightelf]:hover:border-race-nightelf",
        "data-[race=nightelf]:active:border-race-nightelf",
        "data-[race=undead]:hover:border-race-undead",
        "data-[race=undead]:active:border-race-undead",
        "data-[race=neutral]:hover:border-warcraft-gold",
        "data-[race=neutral]:active:border-warcraft-gold",
        "kb-focus:border-warcraft-gold",
        "kb-focus:shadow-focus",
        "in-data-[drag-over=true]:border-warcraft-gold",
        "in-data-[drag-over=true]:border-solid",
        "data-[dragging-source=true]:bg-panel-dark",
        "data-[dragging-source=true]:border-warcraft-blue",
        "data-[dragging-source=true]:border-dashed",
        "data-[dragging-source=true]:shadow-bevel",
        "data-[dragging-source=true]:*:invisible",
        "data-[dragging-source=true]:data-[drag-over=true]:border-warcraft-gold",
        "data-[dragging-source=true]:data-[drag-over=true]:border-dashed",
        "[body:has([data-dragging-source=true])_&]:transition-none",
    ],
}

states! {
    FilledTileState,
    Filled => tw![
        "bg-warcraft-bg-panel/95",
        "border-warcraft-blue",
        "shadow-bevel",
    ],
    Command => tw![
        "bg-panel-blue",
        "border-warcraft-blue",
        "shadow-bevel",
    ],
    Selected => tw![
        "bg-warcraft-bg-panel/95",
        "border-warcraft-gold",
        "shadow-glow",
        "data-[race=human]:border-race-human",
        "data-[race=human]:[--glow-color:var(--color-race-human)]", "data-[race=human]:shadow-glow",
        "data-[race=orc]:border-race-orc",
        "data-[race=orc]:[--glow-color:var(--color-race-orc)]", "data-[race=orc]:shadow-glow",
        "data-[race=nightelf]:border-race-nightelf",
        "data-[race=nightelf]:[--glow-color:var(--color-race-nightelf)]", "data-[race=nightelf]:shadow-glow",
        "data-[race=undead]:border-race-undead",
        "data-[race=undead]:[--glow-color:var(--color-race-undead)]", "data-[race=undead]:shadow-glow",
        "data-[race=neutral]:border-warcraft-gold",
        "data-[race=neutral]:shadow-glow",
    ],
}
