use super::state::FilledTileState;
use tw_macro::tw;

classes! {
    base: tw![
        "relative",
        "w-full",
        "aspect-square",
        "[container-type:inline-size]",
        "overflow-hidden",
        "border-[2cqi]",
        "rounded-[5.2cqi]",
        "[transition:border-color_0.12s_ease,box-shadow_0.12s_ease]",
        "touch-pan-y",
        "outline-none",
        "hover:border-warcraft-gold",
        "active:border-warcraft-gold",
        "data-[race=human]:hover:border-race-human",
        "data-[race=human]:active:border-race-human",
        "data-[race=orc]:hover:border-race-orc",
        "data-[race=orc]:active:border-race-orc",
        "data-[race=nightelf]:hover:border-race-nightelf",
        "data-[race=nightelf]:active:border-race-nightelf",
        "data-[race=undead]:hover:border-race-undead",
        "data-[race=undead]:active:border-race-undead",
        "data-[race=neutral]:hover:border-warcraft-gold",
        "data-[race=neutral]:active:border-warcraft-gold",
        "kb-focus:border-warcraft-gold",
        "kb-focus:[box-shadow:var(--shadow-focus-gold)]",
        "[[data-drag-over=true]_&]:border-warcraft-gold",
        "[[data-drag-over=true]_&]:border-solid",
        "data-[dragging-source=true]:bg-panel-dark-diag-85",
        "data-[dragging-source=true]:border-warcraft-blue-bright",
        "data-[dragging-source=true]:border-dashed",
        "data-[dragging-source=true]:shadow-bevel-hl",
        "data-[dragging-source=true]:[&>*]:invisible",
        "data-[dragging-source=true]:data-[drag-over=true]:border-warcraft-gold",
        "data-[dragging-source=true]:data-[drag-over=true]:border-dashed",
        "[body:has([data-dragging-source=true])_&]:transition-none",
    ],
}

states! {
    FilledTileState,
    Filled => tw![
        "bg-warcraft-bg-panel/95",
        "border-warcraft-blue-bright",
        "shadow-bevel-hl",
    ],
    Command => tw![
        "bg-panel-blue-diag-95",
        "border-warcraft-blue-bright",
        "shadow-bevel-hl",
    ],
    Selected => tw![
        "bg-warcraft-bg-panel/95",
        "border-warcraft-gold",
        "[box-shadow:var(--shadow-glow-gold)]",
        "data-[race=human]:border-race-human",
        "data-[race=human]:[box-shadow:var(--shadow-glow-human-select)]",
        "data-[race=orc]:border-race-orc",
        "data-[race=orc]:[box-shadow:var(--shadow-glow-orc-select)]",
        "data-[race=nightelf]:border-race-nightelf",
        "data-[race=nightelf]:[box-shadow:var(--shadow-glow-nightelf-select)]",
        "data-[race=undead]:border-race-undead",
        "data-[race=undead]:[box-shadow:var(--shadow-glow-undead-select)]",
        "data-[race=neutral]:border-warcraft-gold",
        "data-[race=neutral]:[box-shadow:var(--shadow-glow-gold-select)]",
    ],
}
