use tw_macro::tw;
use warcraft_api::Race;

// Phone/tablet: a swipe-scannable banner-card strip — each tab a chunky fixed
// height (all five share the row) with tighter type and a slightly softer banner
// brightness than the desktop row.

classes! {
    base: tw![
        "group",
        "relative",
        "flex-1",
        "min-w-0",
        "p-0",
        "border",
        "border-warcraft-blue-bright-deep",
        "rounded-card",
        "text-warcraft-text-primary",
        "text-[1.5rem]",
        "uppercase",
        "tracking-[0.08em]",
        "text-center",
        "transition-[border-color,box-shadow,transform]",
        "duration-150",
        "overflow-hidden",
        "isolate",
        "flex",
        "items-end",
        "justify-center",
        "min-h-[clamp(4rem,7vw,7rem)]",
        "min-w-[clamp(4.5rem,8vw,9rem)]",
        "[text-shadow:1px_1px_0_var(--color-warcraft-shadow),-1px_1px_0_var(--color-warcraft-shadow),1px_-1px_0_var(--color-warcraft-shadow),-1px_-1px_0_var(--color-warcraft-shadow),0_0_8px_color-mix(in_oklab,var(--color-warcraft-shadow)_85%,transparent)]",
        "before:content-['']",
        "before:absolute",
        "before:inset-0",
        "before:bg-contain",
        "before:bg-no-repeat",
        "before:bg-center",
        "before:brightness-150",
        "before:saturate-125",
        "before:z-0",
        "before:pointer-events-none",
        "before:block",
        "after:content-['']",
        "after:absolute",
        "after:inset-0",
        "after:bg-[linear-gradient(180deg,color-mix(in_oklab,var(--color-warcraft-shadow)_0%,transparent)_0%,color-mix(in_oklab,var(--color-warcraft-shadow)_0%,transparent)_45%,color-mix(in_oklab,var(--color-warcraft-shadow)_55%,transparent)_75%,color-mix(in_oklab,var(--color-warcraft-shadow)_85%,transparent)_100%)]",
        "after:z-[1]",
        "after:pointer-events-none",
        "after:block",
        "hover:text-white",
        "focus:outline-none",
        "data-[active=true]:text-white",
        "kb-focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:border-white",
        "kb-focus:shadow-ring-hl-3",
    ],
    mobile: tw![
        "mobile:h-[clamp(112px,36vw,200px)]",
        "mobile:min-h-0",
        "mobile:text-[clamp(0.75rem,2.6vw,1rem)]",
        "mobile:before:brightness-[1.35]",
        "mobile:before:saturate-[1.2]",
    ],
    tablet: tw![
        "tablet:h-[clamp(112px,36vw,200px)]",
        "tablet:min-h-0",
        "tablet:text-[clamp(0.75rem,2.6vw,1rem)]",
        "tablet:before:brightness-[1.35]",
        "tablet:before:saturate-[1.2]",
    ],
    laptop: tw!["laptop:min-h-[clamp(3rem,6vh,5rem)]"],
}

states! {
    Race,
    Human => tw![
        "bg-[linear-gradient(180deg,#173266_0%,#050a1a_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-human.png')]",
        "hover:border-race-human",
        "hover:shadow-glow-human-12",
        "data-[active=true]:border-race-human",
        "data-[active=true]:bg-[linear-gradient(180deg,#173266_0%,#0a1432_100%)]",
        "data-[active=true]:shadow-glow-human-22",
    ],
    Orc => tw![
        "bg-[linear-gradient(180deg,#5a1212_0%,#050a1a_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-orc.png')]",
        "hover:border-race-orc",
        "hover:shadow-glow-orc-12",
        "data-[active=true]:border-race-orc",
        "data-[active=true]:bg-[linear-gradient(180deg,#5a1212_0%,#0a1432_100%)]",
        "data-[active=true]:shadow-glow-orc-22",
    ],
    Nightelf => tw![
        "bg-[linear-gradient(180deg,#0c4348_0%,#050a1a_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-nightelf.png')]",
        "hover:border-race-nightelf",
        "hover:shadow-glow-nightelf-12",
        "data-[active=true]:border-race-nightelf",
        "data-[active=true]:bg-[linear-gradient(180deg,#0c4348_0%,#0a1432_100%)]",
        "data-[active=true]:shadow-glow-nightelf-22",
    ],
    Undead => tw![
        "bg-[linear-gradient(180deg,#321650_0%,#050a1a_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-undead.png')]",
        "hover:border-race-undead",
        "hover:shadow-glow-undead-12",
        "data-[active=true]:border-race-undead",
        "data-[active=true]:bg-[linear-gradient(180deg,#321650_0%,#0a1432_100%)]",
        "data-[active=true]:shadow-glow-undead-22",
    ],
    Neutral => tw![
        "bg-[linear-gradient(180deg,#4a3d14_0%,#050a1a_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-random.png')]",
        "hover:border-warcraft-gold",
        "hover:shadow-[0_0_12px_color-mix(in_oklab,var(--color-warcraft-gold)_45%,transparent)]",
        "data-[active=true]:border-warcraft-gold",
        "data-[active=true]:bg-[linear-gradient(180deg,#4a3d14_0%,#0a1432_100%)]",
        "data-[active=true]:shadow-[0_0_22px_color-mix(in_oklab,var(--color-warcraft-gold)_45%,transparent),inset_0_0_24px_color-mix(in_oklab,var(--color-warcraft-highlight)_4%,transparent)]",
    ],
}
