use tw_macro::tw;
use warcraft_api::Race;

// Phone/tablet: a swipe-scannable banner-card strip — each tab a chunky fixed
// height (all five share the row) with tighter type and a slightly softer banner
// brightness than the desktop row.

classes! {
    base: tw![
        "group",
        "relative",
        "flex-1",
        "min-w-0",
        "p-0",
        "border",
        "border-warcraft-blue-deep",
        "rounded-card",
        "text-warcraft-text-primary",
        "text-xl",
        "uppercase",
        "tracking-[0.08em]",
        "text-center",
        "transition-[border-color,box-shadow,transform]",
        "duration-150",
        "overflow-hidden",
        "isolate",
        "flex",
        "items-end",
        "justify-center",
        "h-full",
        "[text-shadow:1px_1px_0_var(--color-warcraft-shadow),-1px_1px_0_var(--color-warcraft-shadow),1px_-1px_0_var(--color-warcraft-shadow),-1px_-1px_0_var(--color-warcraft-shadow),0_0_8px_color-mix(in_oklab,var(--color-warcraft-shadow)_85%,transparent)]",
        "before:content-['']",
        "before:absolute",
        "before:inset-0",
        "before:bg-contain",
        "before:bg-no-repeat",
        "before:bg-center",
        "before:brightness-150",
        "before:saturate-125",
        "before:z-0",
        "before:pointer-events-none",
        "before:block",
        "after:content-['']",
        "after:absolute",
        "after:inset-0",
        "after:bg-[linear-gradient(180deg,color-mix(in_oklab,var(--color-warcraft-shadow)_0%,transparent)_0%,color-mix(in_oklab,var(--color-warcraft-shadow)_0%,transparent)_45%,color-mix(in_oklab,var(--color-warcraft-shadow)_55%,transparent)_75%,color-mix(in_oklab,var(--color-warcraft-shadow)_85%,transparent)_100%)]",
        "after:z-[1]",
        "after:pointer-events-none",
        "after:block",
        "hover:text-white",
        "focus:outline-none",
        "data-[active=true]:text-white",
        "kb-focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:border-white",
        "kb-focus:shadow-ring-hl-3",
    ],
    mobile: tw![
        "mobile:text-sm",
        "mobile:before:brightness-[1.35]",
        "mobile:before:saturate-[1.2]",
    ],
    tablet: tw![
        "tablet:text-sm",
        "tablet:before:brightness-[1.35]",
        "tablet:before:saturate-[1.2]",
    ],
}

states! {
    Race,
    Human => tw![
        "bg-[linear-gradient(180deg,var(--color-race-human-banner)_0%,var(--color-warcraft-bg-base)_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-human.png')]",
        "hover:border-race-human",
        "hover:shadow-glow-human-select",
        "data-[active=true]:border-race-human",
        "data-[active=true]:bg-[linear-gradient(180deg,var(--color-race-human-banner)_0%,var(--color-warcraft-bg-abyss)_100%)]",
        "data-[active=true]:shadow-glow-human-strong",
    ],
    Orc => tw![
        "bg-[linear-gradient(180deg,var(--color-race-orc-strong)_0%,var(--color-warcraft-bg-base)_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-orc.png')]",
        "hover:border-race-orc",
        "hover:shadow-glow-orc-select",
        "data-[active=true]:border-race-orc",
        "data-[active=true]:bg-[linear-gradient(180deg,var(--color-race-orc-strong)_0%,var(--color-warcraft-bg-abyss)_100%)]",
        "data-[active=true]:shadow-glow-orc-strong",
    ],
    Nightelf => tw![
        "bg-[linear-gradient(180deg,var(--color-race-nightelf-banner)_0%,var(--color-warcraft-bg-base)_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-nightelf.png')]",
        "hover:border-race-nightelf",
        "hover:shadow-glow-nightelf-select",
        "data-[active=true]:border-race-nightelf",
        "data-[active=true]:bg-[linear-gradient(180deg,var(--color-race-nightelf-banner)_0%,var(--color-warcraft-bg-abyss)_100%)]",
        "data-[active=true]:shadow-glow-nightelf-strong",
    ],
    Undead => tw![
        "bg-[linear-gradient(180deg,var(--color-race-undead-banner)_0%,var(--color-warcraft-bg-base)_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-undead.png')]",
        "hover:border-race-undead",
        "hover:shadow-glow-undead-select",
        "data-[active=true]:border-race-undead",
        "data-[active=true]:bg-[linear-gradient(180deg,var(--color-race-undead-banner)_0%,var(--color-warcraft-bg-abyss)_100%)]",
        "data-[active=true]:shadow-glow-undead-strong",
    ],
    Neutral => tw![
        "bg-[linear-gradient(180deg,var(--color-race-neutral-strong)_0%,var(--color-warcraft-bg-base)_100%)]",
        "before:bg-[url('/warcraft-hotkey-editor/webui/common/dark-banner-random.png')]",
        "hover:border-warcraft-gold",
        "hover:shadow-glow-12-2",
        "data-[active=true]:border-warcraft-gold",
        "data-[active=true]:bg-[linear-gradient(180deg,var(--color-race-neutral-strong)_0%,var(--color-warcraft-bg-abyss)_100%)]",
        "data-[active=true]:shadow-glow-gold-strong",
    ],
}
