use tw_macro::tw;

classes! {
    base: tw![
        "pointer-events-none",
        "z-1200",
        "w-max",
        "max-w-152",
        "px-4",
        "py-3",
        "border",
        "border-warcraft-gold",
        "rounded-control",
        "text-xl",
        "leading-body",
        "text-center",
        "whitespace-normal",
        "text-warcraft-gold",
        "bg-panel-dark",
        "text-shadow-drop",
        "shadow-raised",
        "opacity-0",
        "transition-opacity",
        "duration-base",
        "delay-400",
        "group-hover/tooltip:opacity-100",
        "group-focus-visible/tooltip:opacity-100",
        "supports-[anchor-name:--a]:fixed",
        "supports-[anchor-name:--a]:[position-anchor:--tooltip-anchor]",
        "supports-[anchor-name:--a]:[position-try-fallbacks:flip-block,flip-inline]",
        "supports-[anchor-name:--a]:m-[0.6rem_0]",
        "not-supports-[anchor-name:--a]:absolute",
        "supports-[anchor-name:--a]:[position-area:block-start]",
        "not-supports-[anchor-name:--a]:top-auto",
        "not-supports-[anchor-name:--a]:bottom-[calc(100%+0.6rem)]",
        "not-supports-[anchor-name:--a]:left-1/2",
        "not-supports-[anchor-name:--a]:-translate-x-1/2",
    ],
}
