use tw_macro::tw;
classes! {
    base: tw![
        "appearance-none",
        "inline-flex",
        "items-center",
        "justify-center",
        "flex-none",
        "w-8",
        "h-8",
        "border-2",
        "rounded-card",
        "border-warcraft-gold",
        "bg-warcraft-gold-dark/75",
        "cursor-pointer",
        "transition-[background,box-shadow]",
        "hover:bg-warcraft-gold/12",
        "hover:shadow-glow-soft",
        "checked:bg-warcraft-gold/18",
        "checked:shadow-ring",
        "checked:after:content-['']",
        "checked:after:w-[0.6rem]",
        "checked:after:h-[1.05rem]",
        "checked:after:translate-y-[-0.18rem]",
        "checked:after:border-solid",
        "checked:after:border-warcraft-gold",
        "checked:after:[border-width:0_0.3rem_0.3rem_0]",
        "checked:after:rotate-45",
        "checked:after:drop-shadow-drop",
        "kb-focus:outline-none",
        "kb-focus:shadow-focus",
    ],
    mobile: tw![
        "mobile:w-5.5",
        "mobile:h-5.5",
        "mobile:rounded-tile",
        "mobile:checked:after:w-1.5",
        "mobile:checked:after:h-2.75",
        "mobile:checked:after:-translate-y-0.5",
        "mobile:checked:after:[border-width:0_3px_3px_0]",
    ],
    tablet: tw![
        "tablet:w-5.5",
        "tablet:h-5.5",
        "tablet:rounded-tile",
        "tablet:checked:after:w-1.5",
        "tablet:checked:after:h-2.75",
        "tablet:checked:after:-translate-y-0.5",
        "tablet:checked:after:[border-width:0_3px_3px_0]",
    ],
}
