use tw_macro::tw;
classes! {
    base: tw![
        "px-12",
        "py-6",
        "border",
        "border-warcraft-gold-border",
        "rounded-panel",
        "text-2xl",
        "tracking-[0.06em]",
        "uppercase",
        "text-warcraft-gold",
        "cursor-pointer",
        "[background:linear-gradient(180deg,color-mix(in_oklab,var(--color-warcraft-gold-dark)_65%,transparent)_0%,color-mix(in_oklab,var(--color-warcraft-shadow)_65%,transparent)_100%)]",
        "text-shadow-drop",
        "[transition:border-color_0.15s_ease,background_0.15s_ease,box-shadow_0.15s_ease]",
        "hover:border-warcraft-gold",
        "hover:[background:linear-gradient(180deg,color-mix(in_oklab,var(--color-warcraft-gold)_18%,transparent)_0%,color-mix(in_oklab,var(--color-warcraft-gold-dark)_65%,transparent)_100%)]",
        "hover:[box-shadow:var(--shadow-glow-12-2)]",
        "active:translate-y-[1px]",
    ],
    mobile: tw![
        "mobile:w-full",
        "mobile:min-h-[44px]",
        "mobile:px-6",
        "mobile:py-3",
        "mobile:text-base",
    ],
    tablet: tw![
        "tablet:w-full",
        "tablet:min-h-[44px]",
        "tablet:px-6",
        "tablet:py-3",
        "tablet:text-base",
    ],
}
