use tw_macro::tw;

classes! {
    base: tw![
        "flex",
        "flex-col",
        "items-stretch",
        "flex-none",
        "gap-5",
        "py-8",
        "px-9",
        "overflow-hidden",
        "border",
        "border-(--race-color,var(--color-warcraft-gold))",
        "rounded-panel",
        "bg-panel-gold-resting",
        "shadow-glow-soft",
    ],
    mobile: tw![
        "mobile:w-full",
        "mobile:max-w-full",
        "mobile:min-w-0",
        "mobile:flex-1",
        "mobile:min-h-0",
        "mobile:box-border",
        "mobile:flex-nowrap",
        "mobile:justify-start",
        "mobile:text-(length:--override-font-size,3.8cqi)",
        "mobile:gap-[0.6em]",
        "mobile:p-[0.8em]",
    ],
    tablet: tw![
        "tablet:w-full",
        "tablet:max-w-full",
        "tablet:min-w-0",
        "tablet:box-border",
        "tablet:flex-nowrap",
        "tablet:justify-start",
        "tablet:gap-y-1.5",
        "tablet:gap-x-2.5",
        "tablet:py-2.5",
        "tablet:px-3",
    ],
}
