[package]
name = "hotkey-editor"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Web-based Warcraft III CustomKeys.txt editor."

[lib]
path = "src/lib.rs"

[[bin]]
name = "hotkey-editor"
path = "src/main.rs"

[dependencies]
browser-kit = { workspace = true }
dioxus = { workspace = true, features = ["web", "router", "launch", "macro"] }
dioxus-primitives = { workspace = true }
dioxus-cli-config = { version = "0.7.9", features = ["web"] }
wasm-bindgen = "0.2.126"
web-sys = { version = "0.3", features = [
  "AddEventListenerOptions",
  "Event",
  "HtmlInputElement",
  "HtmlElement",
  "Element",
  "Node",
  "NodeList",
  "KeyboardEvent",
  "PointerEvent",
  "MouseEvent",
  "DomRect",
  "Document",
  "EventTarget",
  "DomTokenList",
  "CssStyleDeclaration",
  "ScrollIntoViewOptions",
  "ScrollLogicalPosition",
  "Window",
  "Storage",
  "History",
  "Location",
  "UrlSearchParams",
] }
gloo-timers = { version = "0.4.0", features = ["futures"] }
console_error_panic_hook = "0.1.7"
warcraft-api = { workspace = true }
warcraft-database = { workspace = true }
ddd = { workspace = true }
dioxus-kit = { workspace = true }
tw-macro = { workspace = true, features = ["dioxus"] }
warcraft-keybinds = { workspace = true }
