server {
    listen 80;
    root /usr/share/nginx/html;

    location = / {
        return 301 /warcraft-hotkey-editor/;
    }

    location /warcraft-hotkey-editor/ {
        try_files $uri $uri/ /warcraft-hotkey-editor/index.html;
    }

    location /_dioxus {
        access_log off;
        return 404;
    }
}
