use tw_macro::tw;
// The app shell centres the routed page in a single full-bleed column — no padding, so
// the shell (and its header) spans the whole viewport width and its content reaches
// every edge. It sets no inter-section spacing: each section (header, the view, footer)
// owns its own spacing, so the shell never reaches across the wall to space its children.
// It also owns the app-wide foundational resets that used to live as global rules in
// tailwind.input.css: they are `.app`-scoped, so they are inline descendant utilities on
// this root, not global CSS.

// Phone/tablet: full-bleed with no padding at all (the shell spans the whole viewport and
// its content reaches every edge), a content-driven height above the dvh floor.

classes! {
    base: tw![
        "mx-auto",
        "flex",
        "flex-col",
        "min-h-dvh",
        "min-w-0",
        "max-w-full",
        "overflow-x-clip",
        "text-warcraft-text-primary",
        "[-webkit-text-size-adjust:100%]",
        "[text-size-adjust:100%]",
        "[&_button]:cursor-pointer",
        "before:content-['']",
        "before:fixed",
        "before:inset-0",
        "before:-z-10",
        "before:bg-warcraft-bg-base",
        "before:bg-panel-header",
        "before:bg-no-repeat",
        "before:bg-fixed",
        "before:bg-size-[100%_100%]",
        "[@media(hover:none)]:[&_button:hover]:[background:inherit]",
        "[@media(hover:none)]:[&_button:hover]:text-inherit",
        "[@media(hover:none)]:[&_button:hover]:border-inherit",
        "[@media(hover:none)]:[&_button:hover]:shadow-none",
        "[@media(hover:none)]:[&_button:hover]:text-shadow-none",
        "[@media(hover:none)]:[&_button:hover]:transform-none",
        "[@media(hover:none)]:[&_a:hover]:[background:inherit]",
        "[@media(hover:none)]:[&_a:hover]:text-inherit",
        "[@media(hover:none)]:[&_a:hover]:border-inherit",
        "[@media(hover:none)]:[&_a:hover]:shadow-none",
        "[@media(hover:none)]:[&_a:hover]:text-shadow-none",
        "[@media(hover:none)]:[&_a:hover]:transform-none",
        "scrollbar-thin",
        "[scrollbar-color:color-mix(in_oklab,var(--color-warcraft-gold)_45%,transparent)_transparent]",
        "[&_*::-webkit-scrollbar]:w-2",
        "[&_*::-webkit-scrollbar]:h-2",
        "[&_*::-webkit-scrollbar-track]:rounded-control",
        "[&_*::-webkit-scrollbar-track]:[background:color-mix(in_oklab,var(--color-warcraft-bg-base)_45%,transparent)]",
        "[&_*::-webkit-scrollbar-thumb]:rounded-control",
        "[&_*::-webkit-scrollbar-thumb]:[background:color-mix(in_oklab,var(--color-warcraft-gold)_45%,transparent)]",
        "[&_*::-webkit-scrollbar-thumb]:hover:[background:var(--color-warcraft-gold)]",
        "[&_*::-webkit-scrollbar-corner]:[background:color-mix(in_oklab,var(--color-warcraft-bg-base)_45%,transparent)]",
    ],
    mobile: tw![
        "mobile:h-auto",
        "mobile:overflow-y-visible",
        "mobile:**:min-w-0",
        "mobile:[&_img]:max-w-full",
        "mobile:[&_img]:h-auto",
        "mobile:[&_svg]:max-w-full",
        "mobile:[&_svg]:h-auto",
        "mobile:[&_button]:[-webkit-tap-highlight-color:transparent]",
        "mobile:[&_button]:touch-manipulation",
        "mobile:[&_a]:[-webkit-tap-highlight-color:transparent]",
        "mobile:[&_a]:touch-manipulation",
        "mobile:**:[[role=button]]:[-webkit-tap-highlight-color:transparent]",
        "mobile:**:[[role=button]]:touch-manipulation",
        "mobile:[&_input]:touch-manipulation",
    ],
    tablet: tw![
        "tablet:h-auto",
        "tablet:overflow-y-visible",
        "tablet:**:min-w-0",
        "tablet:[&_img]:max-w-full",
        "tablet:[&_img]:h-auto",
        "tablet:[&_svg]:max-w-full",
        "tablet:[&_svg]:h-auto",
        "tablet:[&_button]:[-webkit-tap-highlight-color:transparent]",
        "tablet:[&_button]:touch-manipulation",
        "tablet:[&_a]:[-webkit-tap-highlight-color:transparent]",
        "tablet:[&_a]:touch-manipulation",
        "tablet:**:[[role=button]]:[-webkit-tap-highlight-color:transparent]",
        "tablet:**:[[role=button]]:touch-manipulation",
        "tablet:[&_input]:touch-manipulation",
    ],
}
