use tw_macro::tw;
classes! {
    base: tw![
        "inline-flex",
        "items-center",
        "justify-center",
        "min-h-12",
        "px-7",
        "py-3",
        "border",
        "border-warcraft-gold",
        "rounded-panel",
        "text-warcraft-gold",
        "text-lg",
        "tracking-caps",
        "uppercase",
        "cursor-pointer",
        "bg-panel-gold-resting",
        "shadow-glow",
        "transition-[background,box-shadow]",
        "duration-fast",
        "focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]",
        "kb-focus:shadow-focus",
        "hover:bg-panel-gold",
        "hover:shadow-glow-strong",
    ],
    mobile: tw![
        "mobile:px-4",
        "mobile:py-2",
        "mobile:text-sm",
    ],
}
