use tw_macro::tw;
classes! {
    base: tw![
        "inline-flex",
        "items-center",
        "justify-center",
        "size-full",
        "p-0",
        "border-[1.25cqi]",
        "border-warcraft-gold-border",
        "rounded-[15cqi]",
        "text-warcraft-text-secondary",
        "cursor-pointer",
        "bg-panel-gold-resting",
        "transition-[border-color,color,background,box-shadow]",
        "focus:outline-none",
        "focus-visible:border-white",
        "focus-visible:text-white",
        "focus-visible:[--focus-color:var(--color-warcraft-highlight)]",
        "focus-visible:shadow-focus",
        "hover:border-warcraft-gold",
        "hover:text-warcraft-gold",
        "hover:bg-panel-gold-active",
        "hover:shadow-glow",
    ],
}
