use tw_macro::tw;

classes! {
    base: tw![
        "@container",
        "group",
        "relative",
        "size-full",
        "min-w-0",
        "p-0",
        "border",
        "border-warcraft-blue-deep",
        "rounded-card",
        "bg-race-banner",
        "text-warcraft-text-primary",
        "text-xl",
        "uppercase",
        "tracking-caps",
        "text-center",
        "transition-[border-color,box-shadow,transform]",
        "duration-base",
        "overflow-hidden",
        "isolate",
        "flex",
        "items-end",
        "justify-center",
        "text-shadow-tab",
        "before:content-['']",
        "before:absolute",
        "before:inset-0",
        "before:[background-image:var(--banner-image)]",
        "before:bg-contain",
        "before:bg-no-repeat",
        "before:bg-center",
        "before:brightness-150",
        "before:saturate-125",
        "before:z-0",
        "before:pointer-events-none",
        "before:block",
        "after:content-['']",
        "after:absolute",
        "after:inset-0",
        "after:bg-scrim-bottom",
        "after:z-1",
        "after:pointer-events-none",
        "after:block",
        "hover:text-white",
        "hover:border-(--race-color)",
        "hover:[--glow-color:var(--race-color)]",
        "hover:shadow-glow",
        "focus:outline-none",
        "kb-focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:border-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]",
        "kb-focus:shadow-focus",
    ],
    mobile: tw![
        "mobile:text-sm",
        "mobile:before:brightness-[1.35]",
        "mobile:before:saturate-[1.2]",
    ],
    tablet: tw![
        "tablet:text-sm",
        "tablet:before:brightness-[1.35]",
        "tablet:before:saturate-[1.2]",
    ],
}
