use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "items-center",
        "gap-[0.4rem]",
        "w-full",
        "text-left",
        "mt-3",
        "mb-1",
        "py-[0.35rem]",
        "px-[0.25rem]",
        "text-md",
        "uppercase",
        "tracking-[0.12em]",
        "border-b",
        "border-warcraft-blue-deep",
        "cursor-pointer",
        "transition-colors",
        "duration-[0.12s]",
        "first:mt-0",
        "text-warcraft-text-faint",
        "hover:text-warcraft-gold",
        "focus:outline-none",
        "kb-focus:text-warcraft-gold",
    ],
    mobile: tw!["mobile:hidden"],
    tablet: tw!["tablet:hidden"],
}
