use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "items-center",
        "gap-1.5",
        "w-full",
        "text-left",
        "mt-3",
        "mb-1",
        "py-1.5",
        "px-1",
        "text-md",
        "uppercase",
        "tracking-[0.12em]",
        "border-b",
        "border-warcraft-blue-deep",
        "cursor-pointer",
        "transition-colors",
        "duration-fast",
        "first:mt-0",
        "text-warcraft-text-faint",
        "hover:text-warcraft-gold",
        "focus:outline-none",
        "kb-focus:text-warcraft-gold",
    ],
    mobile: tw!["mobile:hidden"],
    tablet: tw!["tablet:hidden"],
}
