use tw_macro::tw;
classes! {
    base: tw![
        "inline-flex",
        "items-center",
        "justify-center",
        "w-9",
        "h-9",
        "p-0",
        "bg-transparent",
        "border",
        "border-warcraft-gold/30",
        "rounded-card",
        "text-warcraft-gold/70",
        "text-sm",
        "cursor-pointer",
        "transition-[border-color,color,background]",
        "hover:border-warcraft-gold",
        "hover:text-warcraft-gold",
        "hover:bg-warcraft-gold/8",
        "focus:outline-none",
        "focus-visible:border-white",
        "focus-visible:text-white",
        "focus-visible:[--focus-color:var(--color-warcraft-highlight)]", "focus-visible:shadow-focus",
    ],
}
