use tw_macro::tw;

classes! {
    base: tw![
        "@container",
        "size-full",
        "flex",
        "flex-col",
        "items-center",
        "justify-center",
        "gap-(--slot-frame-gap,--spacing(2))",
        "px-(--slot-frame-pad-x,--spacing(2.5))",
        "py-(--slot-frame-pad-y,--spacing(3.5))",
        "text-center",
        "select-none",
        "border-solid",
        "border-(length:--slot-frame-border,12px)",
        "bg-panel-dark",
        "[border-image-source:var(--wc3-slot-frame)]",
        "[border-image-slice:var(--slot-frame-slice,12_fill)]",
        "[border-image-repeat:stretch]",
        "transition-[filter]",
        "group-hover/tooltip:brightness-[1.18]",
        "group-hover/tooltip:drop-glow",
        "group-focus-visible/tooltip:brightness-[1.25]",
        "group-focus-visible/tooltip:[--glow-color:var(--color-warcraft-highlight)]",
        "group-focus-visible/tooltip:drop-glow",
    ],
    mobile: tw![
        "mobile:border-(length:--slot-frame-border,8px)",
        "mobile:px-(--slot-frame-pad-x,var(--spacing))",
        "mobile:py-(--slot-frame-pad-y,--spacing(2))",
        "mobile:gap-(--slot-frame-gap,var(--spacing))",
    ],
    tablet: tw![
        "tablet:border-(length:--slot-frame-border,8px)",
        "tablet:px-(--slot-frame-pad-x,var(--spacing))",
        "tablet:py-(--slot-frame-pad-y,--spacing(2))",
        "tablet:gap-(--slot-frame-gap,var(--spacing))",
    ],
}
