use tw_macro::tw;
classes! {
    base: tw![
        "hidden",
        "kb-focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]",
        "kb-focus:shadow-focus",
    ],
    mobile: tw![
        "mobile:flex",
        "mobile:items-center",
        "mobile:justify-between",
        "mobile:gap-2.5",
        "mobile:w-full",
        "mobile:min-h-11",
        "mobile:py-2",
        "mobile:px-3.5",
        "mobile:border",
        "mobile:border-warcraft-gold/55",
        "mobile:rounded-card",
        "mobile:cursor-pointer",
        "mobile:uppercase",
        "mobile:text-warcraft-gold",
        "mobile:text-base",
        "mobile:tracking-caps",
        "mobile:bg-panel-gold-resting",
        "mobile:text-shadow-drop",
        "mobile:shadow-glow-soft",
    ],
    tablet: tw![
        "tablet:flex",
        "tablet:items-center",
        "tablet:justify-between",
        "tablet:gap-2.5",
        "tablet:w-full",
        "tablet:min-h-11",
        "tablet:py-2",
        "tablet:px-3.5",
        "tablet:border",
        "tablet:border-warcraft-gold/55",
        "tablet:rounded-card",
        "tablet:cursor-pointer",
        "tablet:uppercase",
        "tablet:text-warcraft-gold",
        "tablet:text-base",
        "tablet:tracking-caps",
        "tablet:bg-panel-gold-resting",
        "tablet:text-shadow-drop",
        "tablet:shadow-glow-soft",
    ],
}
