use tw_macro::tw;
// The search text field. A plain bordered box on the sidebar; on mobile it becomes a
// tall pill with room for the leading magnifier icon and a gold focus glow.

classes! {
    base: tw![
        "flex-1",
        "min-w-0",
        "w-full",
        "bg-warcraft-bg-base/70",
        "border",
        "border-warcraft-blue",
        "rounded-control",
        "text-white",
        "px-4",
        "py-3",
        "text-lg",
        "focus:outline-none",
        "focus:border-warcraft-gold",
        "focus:shadow-glow-soft",
    ],
    mobile: tw![
        "mobile:h-11",
        "mobile:pl-10",
        "mobile:pr-3.5",
        "mobile:py-0",
        "mobile:text-base",
        "mobile:rounded-panel",
        "mobile:bg-panel-dark",
        "mobile:border-warcraft-gold/45",
        "mobile:text-warcraft-text-primary",
        "mobile:tracking-[0.04em]",
        "mobile:shadow-bevel",
        "mobile:placeholder:text-warcraft-text-primary/50",
        "mobile:placeholder:italic",
        "mobile:focus:border-warcraft-gold",
        "mobile:focus:shadow-ring",
        "mobile:[&::-webkit-search-cancel-button]:appearance-none",
    ],
    tablet: tw![
        "tablet:h-11",
        "tablet:pl-10",
        "tablet:pr-3.5",
        "tablet:py-0",
        "tablet:text-base",
        "tablet:rounded-panel",
        "tablet:bg-panel-dark",
        "tablet:border-warcraft-gold/45",
        "tablet:text-warcraft-text-primary",
        "tablet:tracking-[0.04em]",
        "tablet:shadow-bevel",
        "tablet:placeholder:text-warcraft-text-primary/50",
        "tablet:placeholder:italic",
        "tablet:focus:border-warcraft-gold",
        "tablet:focus:shadow-ring",
        "tablet:[&::-webkit-search-cancel-button]:appearance-none",
    ],
}
