use tw_macro::tw;

classes! {
    base: tw![
        "@container",
        "uppercase",
        "leading-none",
        "border-0",
        "cursor-pointer",
        "text-shadow-drop",
        "transition-[color,text-shadow]",
        "hover:text-warcraft-gold",
        "hover:text-shadow-glow",
        "kb-focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:[--glow-color:var(--color-warcraft-highlight)]",
        "kb-focus:text-glow",
        "flex-none",
        "w-full",
        "text-left",
        "py-3",
        "px-3.5",
        "text-base",
        "tracking-label",
        "min-h-11",
        "rounded-tile",
        "whitespace-normal",
        "bg-transparent",
        "text-warcraft-gold/55",
    ],
}
