use tw_macro::tw;
classes! {
    base: tw![
        "inline-flex",
        "items-center",
        "justify-center",
        "min-h-[3rem]",
        "px-7",
        "py-3",
        "border",
        "border-warcraft-gold",
        "rounded-panel",
        "text-warcraft-gold",
        "text-lg",
        "tracking-[0.08em]",
        "uppercase",
        "cursor-pointer",
        "bg-panel-gold-diag-85",
        "shadow-glow-22",
        "transition-[background,box-shadow]",
        "duration-[120ms]",
        "focus:outline-none",
        "focus-visible:border-white",
        "focus-visible:text-white",
        "focus-visible:shadow-ring-hl-3",
        "hover:bg-panel-gold-diag-22",
        "hover:shadow-glow-gold-inset",
    ],
}
