use tw_macro::tw;
classes! {
    base: tw![
        "inline-flex",
        "items-center",
        "justify-center",
        "min-h-12",
        "px-7",
        "py-3",
        "border",
        "border-warcraft-gold",
        "rounded-panel",
        "text-warcraft-gold",
        "text-lg",
        "tracking-[0.08em]",
        "uppercase",
        "cursor-pointer",
        "bg-panel-gold-resting",
        "shadow-glow",
        "transition-[background,box-shadow]",
        "duration-fast",
        "focus:outline-none",
        "focus-visible:border-white",
        "focus-visible:text-white",
        "focus-visible:[--focus-color:var(--color-warcraft-highlight)]", "focus-visible:shadow-focus",
        "hover:bg-panel-gold",
        "hover:shadow-glow-strong",
    ],
}
