use tw_macro::tw;

classes! {
    base: tw![
        "relative",
        "group/tooltip",
        "[anchor-name:--tooltip-anchor]",
        "[anchor-scope:--tooltip-anchor]",
        "min-w-0",
        "w-full",
        "h-[7cqi]",
        "px-1",
        "flex",
        "items-center",
        "justify-center",
        "border",
        "rounded-control",
        "text-[1.7cqi]",
        "leading-none",
        "cursor-pointer",
        "whitespace-nowrap",
        "transition-[border-color,background,box-shadow]",
        "duration-fast",
        "text-shadow-outline",
        "focus:outline-none",
        "kb-focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]",
        "kb-focus:shadow-focus",
        "disabled:cursor-not-allowed",
        "disabled:opacity-85",
        "bg-warcraft-danger-dark/50",
        "border-warcraft-danger-border",
        "text-warcraft-danger-soft",
        "[&:hover:not(:disabled)]:border-warcraft-danger",
        "[&:hover:not(:disabled)]:bg-warcraft-danger-dark/65",
        "[--glow-color:var(--color-warcraft-danger)]",
        "[&:hover:not(:disabled)]:shadow-glow-soft",
    ],
    mobile: tw![
        "mobile:h-(--key-height,11cqi)",
        "mobile:px-1",
        "mobile:text-(length:--key-font,4cqi)",
    ],
}
