$schema: ./cache/schemas/tasks.json

fileGroups:
  configs:
    - "*.toml"
    - "*.lock"
  sources:
    - "src/**/*"
  static-assets:
    - "assets/webui/**/*"
    - "assets/favicon.svg"
    - "public/**/*"
  artifacts:
    - target

implicitDeps:
  - ^:build

implicitInputs:
  - /moon.yml
  - /Cargo.toml
  - /Cargo.lock
  - /flake.nix

tasks:
  rust/build:
    toolchain: rust
    command: cargo build
    options:
      outputStyle: stream
    inputs:
      - "@group(sources)"
      - "@group(configs)"

  rust/fmt:
    toolchain: rust
    command: cargo fmt --all -- --check
    options:
      outputStyle: stream
    inputs:
      - "src/**/*.rs"

  rust/fmt/fix:
    toolchain: rust
    command: cargo fmt --all
    options:
      outputStyle: stream
    inputs:
      - "src/**/*.rs"

  rust/lint:
    toolchain: rust
    command: cargo clippy --all-targets -- -D warnings
    options:
      outputStyle: stream
    inputs:
      - "@group(sources)"
      - "@group(configs)"

  rust/test:
    toolchain: rust
    command: cargo test
    options:
      outputStyle: stream
    inputs:
      - "@group(sources)"
      - "@group(configs)"

  ci:
    options:
      outputStyle: stream
      runInCI: true
    deps:
      - ^:ci
      - rust/fmt
      - rust/lint
      - rust/test
      - rust/build
