use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "flex-col",
        "[grid-column:2/3]",
        "self-start",
        "w-full",
        "min-w-0",
        "min-h-0",
        "max-h-full",
        "py-4", "px-5",
        "pb-5",
        "gap-5",
        "border",
        "border-warcraft-blue-deep",
        "rounded-container",
        "bg-panel-dark-diag-70",
        "shadow-bevel-hl-3",
        "overflow-y-auto",
        "overflow-x-clip",
        "[overscroll-behavior:contain]",
        "[scrollbar-width:thin]",
        "[scrollbar-color:color-mix(in_oklab,var(--color-warcraft-gold)_35%,transparent)_transparent]",
        "[&::-webkit-scrollbar]:w-[5px]",
        "[&::-webkit-scrollbar-track]:bg-transparent",
        "[&::-webkit-scrollbar-thumb]:bg-warcraft-gold/35",
        "[&::-webkit-scrollbar-thumb]:rounded-hairline",
        "[&::-webkit-scrollbar-thumb:hover]:bg-warcraft-gold/55",
    ],
    mobile: tw![
        "mobile:[grid-column:auto]",
        "mobile:self-auto",
        "mobile:max-h-none",
        "mobile:w-full",
        "mobile:box-border",
        "mobile:p-5",
        "mobile:rounded-card",
        "mobile:overflow-visible",
    ],
    tablet: tw![
        "tablet:[grid-column:auto]",
        "tablet:self-stretch",
        "tablet:max-h-none",
        "tablet:w-full",
        "tablet:box-border",
        "tablet:p-5",
        "tablet:rounded-card",
        "tablet:overflow-visible",
    ],
}
