use tw_macro::tw;
classes! {
    base: tw![
        "absolute",
        "-top-1.5",
        "-right-1.5",
        "min-w-4.75",
        "h-4.75",
        "px-1",
        "box-border",
        "inline-flex",
        "items-center",
        "justify-center",
        "rounded-panel",
        "bg-warcraft-bg-panel",
        "border",
        "border-warcraft-blue",
        "text-warcraft-text-secondary",
        "text-base",
        "leading-none",
        "text-shadow-drop",
        "data-[win=true]:border-warcraft-gold",
        "data-[win=true]:text-warcraft-gold",
    ],
    mobile: tw![
        "mobile:min-w-3.75",
        "mobile:h-3.75",
        "mobile:text-sm",
    ],
}
