use tw_macro::tw;
// The hotkey-capture button in the override panel. A square gold-bordered key cap; it
// lights up with a static gold glow while capturing (`data-editing`) and widens for
// multi-character special tokens like Esc / Mouse4 (`data-special`). Class
// `.override-key` is load-bearing (keyboard navigation).

classes! {
    base: tw![
        "w-20",
        "h-20",
        "p-0",
        "flex",
        "items-center",
        "justify-center",
        "bg-warcraft-gold-dark/75",
        "border-2",
        "border-warcraft-gold",
        "rounded-tile",
        "text-warcraft-gold",
        "text-[2rem]",
        "leading-none",
        "uppercase",
        "text-center",
        "cursor-pointer",
        "text-shadow-outline",
        "transition-[box-shadow,border-color]",
        "duration-150",
        "hover:border-warcraft-gold",
        "hover:bg-warcraft-gold/12",
        "hover:shadow-glow-8",
        "focus:outline-none",
        "focus:shadow-[0_0_10px_color-mix(in_oklab,var(--color-warcraft-gold)_50%,transparent)]",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:focus-ring",
        "data-[editing=true]:bg-panel-gold-diag-30",
        "data-[editing=true]:border-warcraft-gold",
        "data-[editing=true]:text-warcraft-gold",
        "data-[editing=true]:shadow-glow-18",
        "data-[special=true]:w-auto",
        "data-[special=true]:min-w-[5rem]",
        "data-[special=true]:px-[0.9rem]",
        "data-[special=true]:text-[1.5rem]",
        "data-[special=true]:normal-case",
        "data-[special=true]:tracking-normal",
        "data-[special=true]:whitespace-nowrap",
    ],
    mobile: tw![
        "mobile:w-[4.6rem]",
        "mobile:h-[4.6rem]",
        "mobile:min-w-[4.6rem]",
        "mobile:min-h-[4.6rem]",
        "mobile:text-[2.2rem]",
        "mobile:data-[special=true]:w-auto",
        "mobile:data-[special=true]:min-w-[4.6rem]",
        "mobile:data-[special=true]:px-[0.8rem]",
        "mobile:data-[special=true]:text-[1.5rem]",
    ],
}
