use tw_macro::tw;
classes! {
    base: tw![
        "group",
        "flex",
        "items-baseline",
        "justify-center",
        "flex-wrap",
        "gap-3",
        "[flex:1_1_auto]",
    ],
    mobile: tw![
        "mobile:hidden",
        "mobile:data-[open=true]:flex",
        "mobile:data-[open=true]:absolute",
        "mobile:data-[open=true]:top-[calc(100%-0.25rem)]",
        "mobile:data-[open=true]:left-3",
        "mobile:data-[open=true]:right-3",
        "mobile:data-[open=true]:z-[6]",
        "mobile:data-[open=true]:flex-col",
        "mobile:data-[open=true]:items-stretch",
        "mobile:data-[open=true]:gap-[0.15rem]",
        "mobile:data-[open=true]:p-[0.4rem]",
        "mobile:data-[open=true]:bg-panel-dark-solid-2",
        "mobile:data-[open=true]:border",
        "mobile:data-[open=true]:border-warcraft-gold/45",
        "mobile:data-[open=true]:rounded-panel",
        "mobile:data-[open=true]:shadow-elevation-2",
    ],
    tablet: tw![
        "tablet:hidden",
        "tablet:data-[open=true]:flex",
        "tablet:data-[open=true]:absolute",
        "tablet:data-[open=true]:top-[calc(100%-0.25rem)]",
        "tablet:data-[open=true]:left-3",
        "tablet:data-[open=true]:right-3",
        "tablet:data-[open=true]:z-[6]",
        "tablet:data-[open=true]:flex-col",
        "tablet:data-[open=true]:items-stretch",
        "tablet:data-[open=true]:gap-[0.15rem]",
        "tablet:data-[open=true]:p-[0.4rem]",
        "tablet:data-[open=true]:bg-panel-dark-solid-2",
        "tablet:data-[open=true]:border",
        "tablet:data-[open=true]:border-warcraft-gold/45",
        "tablet:data-[open=true]:rounded-panel",
        "tablet:data-[open=true]:shadow-elevation-2",
    ],
}
