use tw_macro::tw;
classes! {
    base: tw![
        "px-12",
        "py-6",
        "border",
        "border-warcraft-gold-border",
        "rounded-panel",
        "text-2xl",
        "tracking-caps",
        "uppercase",
        "whitespace-nowrap",
        "text-warcraft-gold",
        "cursor-pointer",
        "bg-panel-gold-resting",
        "text-shadow-drop",
        "transition-[border-color,background,box-shadow]",
        "hover:border-warcraft-gold",
        "hover:bg-panel-gold-active",
        "hover:shadow-glow",
        "active:translate-y-px",
        "kb-focus:outline-none",
        "kb-focus:shadow-focus",
    ],
    mobile: tw![
        "mobile:w-full",
        "mobile:min-h-11",
        "mobile:px-6",
        "mobile:py-3",
        "mobile:text-base",
    ],
    tablet: tw![
        "tablet:w-full",
        "tablet:min-h-11",
        "tablet:px-6",
        "tablet:py-3",
        "tablet:text-base",
    ],
}
