use tw_macro::tw;
classes! {
    base: tw![
        "group",
        "flex",
        "items-center",
        "justify-between",
        "gap-2",
        "w-full",
        "px-2",
        "py-1",
        "whitespace-nowrap",
        "[background:linear-gradient(135deg,color-mix(in_oklab,var(--color-warcraft-gold-dark)_60%,transparent)_0%,color-mix(in_oklab,var(--color-warcraft-shadow)_60%,transparent)_100%)]",
        "border",
        "border-warcraft-gold/45",
        "rounded-tile",
        "text-warcraft-gold",
        "text-md",
        "uppercase",
        "tracking-[0.06em]",
        "text-shadow-drop",
        "cursor-pointer",
        "transition-[border-color,box-shadow]",
        "hover:border-warcraft-gold",
        "hover:shadow-glow-soft",
        "data-[open=true]:border-warcraft-gold",
        "data-[open=true]:shadow-glow",
        "kb-focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]", "kb-focus:shadow-focus",
    ],
    mobile: tw![
        "mobile:w-full",
        "mobile:px-2.5",
        "mobile:py-1",
        "mobile:min-h-8",
        "mobile:text-base",
        "mobile:tracking-[0.04em]",
    ],
    tablet: tw![
        "tablet:w-full",
        "tablet:px-2.5",
        "tablet:py-1",
        "tablet:min-h-8",
        "tablet:text-sm",
        "tablet:tracking-[0.04em]",
    ],
}
