use tw_macro::tw;
classes! {
    base: tw![
        "block",
        "w-full",
        "py-1.5",
        "px-3",
        "bg-transparent",
        "border-none",
        "rounded-tile",
        "text-warcraft-text-secondary",
        "text-lg",
        "leading-title",
        "text-left",
        "cursor-pointer",
        "whitespace-nowrap",
        "[transition:background_0.1s_ease,color_0.1s_ease]",
        "hover:bg-warcraft-gold/12",
        "hover:text-warcraft-gold",
        "data-[active=true]:[background:linear-gradient(135deg,color-mix(in_oklab,var(--color-warcraft-gold)_25%,transparent)_0%,color-mix(in_oklab,var(--color-race-neutral-strong)_70%,transparent)_100%)]",
        "data-[active=true]:text-warcraft-gold",
        "kb-focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:[box-shadow:var(--shadow-ring-hl-2)]",
    ],
    mobile: tw![
        "mobile:px-2.5",
        "mobile:py-1",
        "mobile:min-h-[24px]",
        "mobile:text-base",
    ],
    tablet: tw![
        "tablet:px-2.5",
        "tablet:py-1",
        "tablet:min-h-[24px]",
        "tablet:text-xs",
    ],
    laptop: tw![
        "laptop:px-2",
        "laptop:py-1",
        "laptop:text-base",
    ],
    desktop: tw![
        "desktop:px-2",
        "desktop:py-1",
        "desktop:text-base",
    ],
    qhd: tw![
        "qhd:px-2",
        "qhd:py-1",
        "qhd:text-base",
    ],
    uhd: tw![
        "uhd:px-2",
        "uhd:py-1",
        "uhd:text-base",
    ],
}
