use tw_macro::tw;
classes! {
    base: tw![
        "block",
        "w-full",
        "py-[0.4rem]",
        "px-[0.7rem]",
        "bg-transparent",
        "border-none",
        "rounded-[5px]",
        "text-warcraft-text-secondary",
        "text-lg",
        "leading-title",
        "text-left",
        "cursor-pointer",
        "whitespace-nowrap",
        "[transition:background_0.1s_ease,color_0.1s_ease]",
        "hover:bg-warcraft-gold/12",
        "hover:text-warcraft-gold",
        "data-[active=true]:[background:linear-gradient(135deg,color-mix(in_oklab,var(--color-warcraft-gold)_25%,transparent)_0%,color-mix(in_oklab,var(--color-race-neutral-strong)_70%,transparent)_100%)]",
        "data-[active=true]:text-warcraft-gold",
        "kb-focus:outline-none",
        "kb-focus:text-white",
        "kb-focus:[box-shadow:inset_0_0_0_2px_var(--color-warcraft-highlight)]",
    ],
    mobile: tw![
        "mobile:px-[10px]",
        "mobile:py-[3px]",
        "mobile:min-h-[24px]",
        "mobile:text-base",
    ],
    tablet: tw![
        "tablet:px-[10px]",
        "tablet:py-[3px]",
        "tablet:min-h-[24px]",
        "tablet:text-xs",
    ],
    laptop: tw![
        "laptop:px-[0.55rem]",
        "laptop:py-[0.3rem]",
        "laptop:text-base",
    ],
    desktop: tw![
        "desktop:px-[0.55rem]",
        "desktop:py-[0.3rem]",
        "desktop:text-base",
    ],
    qhd: tw![
        "qhd:px-[0.55rem]",
        "qhd:py-[0.3rem]",
        "qhd:text-base",
    ],
    uhd: tw![
        "uhd:px-[0.55rem]",
        "uhd:py-[0.3rem]",
        "uhd:text-base",
    ],
}
