use tw_macro::tw;

classes! {
    base: tw![
        "@container",
        "relative",
        "z-50",
        "items-center",
        "flex-none",
        "px-4",
        "after:content-['']",
        "after:absolute",
        "after:bottom-0",
        "after:left-4",
        "after:right-4",
        "after:h-px",
        "after:bg-warcraft-gold/40",
        "after:shadow-edge",
    ],
    mobile: tw![
        "mobile:flex",
        "mobile:flex-row",
        "mobile:items-stretch",
        "mobile:justify-between",
        "mobile:sticky",
        "mobile:top-0",
        "mobile:z-60",
        "mobile:pt-2",
        "mobile:pb-2",
        "mobile:after:bg-warcraft-gold/30",
        "mobile:min-h-14",
        "mobile:max-w-full",
        "mobile:w-full",
        "mobile:bg-warcraft-bg-base",
        "mobile:bg-panel-header",
        "mobile:bg-no-repeat",
        "mobile:bg-fixed",
        "mobile:bg-size-[100%_100%]",
    ],
    tablet: tw![
        "tablet:flex",
        "tablet:flex-row",
        "tablet:items-stretch",
        "tablet:justify-between",
        "tablet:sticky",
        "tablet:top-0",
        "tablet:z-60",
        "tablet:pt-2",
        "tablet:pb-2",
        "tablet:after:bg-warcraft-gold/30",
        "tablet:min-h-14",
        "tablet:max-w-full",
        "tablet:w-full",
        "tablet:bg-warcraft-bg-base",
        "tablet:bg-panel-header",
        "tablet:bg-no-repeat",
        "tablet:bg-fixed",
        "tablet:bg-size-[100%_100%]",
    ],
    laptop: tw![
        "laptop:grid",
        "laptop:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]",
        "laptop:items-stretch",
        "laptop:min-h-18",
        "laptop:gap-[1cqi]",
        "laptop:py-[0.7cqi]",
    ],
    desktop: tw![
        "desktop:grid",
        "desktop:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]",
        "desktop:items-stretch",
        "desktop:min-h-20",
        "desktop:gap-[1cqi]",
        "desktop:py-[0.7cqi]",
    ],
    qhd: tw![
        "qhd:grid",
        "qhd:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]",
        "qhd:items-stretch",
        "qhd:min-h-28",
        "qhd:gap-[1cqi]",
        "qhd:py-[0.7cqi]",
    ],
    uhd: tw![
        "uhd:grid",
        "uhd:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]",
        "uhd:items-stretch",
        "uhd:min-h-34",
        "uhd:gap-[1cqi]",
        "uhd:py-[0.7cqi]",
    ],
}
