use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "flex-col",
        "col-[2/3]",
        "self-start",
        "w-full",
        "min-w-0",
        "min-h-0",
        "max-h-full",
        "py-4",
        "px-5",
        "pb-5",
        "gap-5",
        "border",
        "border-warcraft-blue-deep",
        "rounded-container",
        "bg-panel-dark",
        "shadow-bevel",
        "overflow-y-auto",
        "overflow-x-clip",
        "overscroll-contain",
    ],
    mobile: tw![
        "mobile:col-auto",
        "mobile:self-auto",
        "mobile:max-h-none",
        "mobile:w-full",
        "mobile:box-border",
        "mobile:p-5",
        "mobile:rounded-card",
        "mobile:overflow-visible",
    ],
    tablet: tw![
        "tablet:col-auto",
        "tablet:self-stretch",
        "tablet:max-h-none",
        "tablet:w-full",
        "tablet:box-border",
        "tablet:p-5",
        "tablet:rounded-card",
        "tablet:overflow-visible",
    ],
}
