use tw_macro::tw;
classes! {
    base: tw![
        "flex",
        "items-center",
        "justify-between",
        "gap-2",
        "w-full",
        "px-2",
        "py-1",
        "whitespace-nowrap",
        "bg-panel-gold-resting",
        "border",
        "border-warcraft-gold/45",
        "rounded-tile",
        "text-warcraft-gold",
        "text-md",
        "uppercase",
        "tracking-caps",
        "text-shadow-drop",
        "cursor-pointer",
        "transition-[border-color,box-shadow]",
        "hover:border-warcraft-gold",
        "hover:shadow-glow-soft",
        "kb-focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]",
        "kb-focus:shadow-focus",
    ],
    mobile: tw![
        "mobile:w-full",
        "mobile:px-2.5",
        "mobile:py-1",
        "mobile:min-h-8",
        "mobile:text-base",
        "mobile:tracking-label",
    ],
    tablet: tw![
        "tablet:w-full",
        "tablet:px-2.5",
        "tablet:py-1",
        "tablet:min-h-8",
        "tablet:text-sm",
        "tablet:tracking-label",
    ],
}
