use tw_macro::tw;

classes! {
    base: tw![
        "relative",
        "group/tooltip",
        "[anchor-name:--tooltip-anchor]",
        "[anchor-scope:--tooltip-anchor]",
        "min-w-0",
        "w-[6cqi]",
        "h-[7cqi]",
        "px-1",
        "flex",
        "items-center",
        "justify-center",
        "border",
        "rounded-control",
        "text-[1.7cqi]",
        "leading-none",
        "cursor-pointer",
        "whitespace-nowrap",
        "transition-[border-color,background,box-shadow]", "duration-fast",
        "text-shadow-outline",
        "focus:outline-none",
        "kb-focus:outline-none",
        "kb-focus:border-white",
        "kb-focus:text-white",
        "kb-focus:[--focus-color:var(--color-warcraft-highlight)]", "kb-focus:shadow-focus",
        "data-[wide=true]:w-[12cqi]",
        "disabled:cursor-not-allowed",
        "disabled:opacity-85",
        "[background:color-mix(in_oklab,var(--color-race-orc-strong)_50%,transparent)]",
        "border-race-orc-strong",
        "text-race-orc",
        "[&:hover:not(:disabled)]:border-warcraft-danger",
        "[&:hover:not(:disabled)]:[background:color-mix(in_oklab,var(--color-race-orc-strong)_55%,transparent)]",
        "[--glow-color:var(--color-warcraft-danger)]",
        "[&:hover:not(:disabled)]:shadow-glow-soft",
    ],
    mobile: tw![
        "mobile:w-[7cqi]",
        "mobile:h-[8.5cqi]",
        "mobile:p-0",
        "mobile:text-[1.6cqi]",
        "mobile:data-[wide=true]:w-[14cqi]",
    ],
}
